# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE actstream_action ALTER COLUMN data TYPE JSONB USING data::JSONB;"),
    ]
